version: '2'
services:
  droppy:
    container_name: droppy
    image: viniciusecortez/droppy
    build: .
    ports:
      - '0.0.0.0:80:8989'
    volumes:
      - ./config:/config
      - ./data:/files
    restart: unless-stopped